(function(){
  const translations = {
    en: {
      'nav.demo':'BOOK FREE DEMO','nav.services':'Services','nav.technology':'Robotic Mowing','nav.why':'Why RoboGardener','nav.commercial':'Commercial','nav.areas':'Service Areas','nav.cta':'Get a Free Quote',
      'hero.eyebrow':'SMARTER LAWN CARE FOR MELBOURNE','hero.title':'A Better Lawn<br><span>Smarter Mowing</span><br>Professional Care','hero.desc':'Robotic mowing technology combined with professional lawn-care expertise for Melbourne homes and commercial properties.','hero.cta1':'Get a Free Lawn Assessment','hero.cta2':'Explore Our Services','hero.proof1':'PhD-qualified horticultural expertise','hero.proof2':'18 years lawn-care experience','hero.proof3':'Quiet, consistent robotic mowing','hero.trust':'PROFESSIONAL OVERSIGHT','hero.phd':'Dr. Bill · PhD in Horticulture','hero.exp':'18 Years Lawn-Care Experience',
      'market.eyebrow':'WHO WE SERVE','market.title':'Professional lawn care for homes and managed properties','market.res.title':'Residential','market.res.desc':'Reliable lawn care tailored to private homes and residential properties.','market.res.i1':'Residential Homes','market.res.i2':'Larger Residential Properties','market.res.i3':'Private Retirement Residences','market.com.title':'Commercial','market.com.desc':'Scalable grounds care for organisations, shared properties and facilities.','market.com.i1':'Commercial Properties','market.com.i2':'Strata & Body Corporate','market.com.i3':'Schools & Childcare','market.com.i4':'Retirement Living & Managed Communities','market.com.i5':'Offices & Facilities',
      'tech.eyebrow':'TECHNOLOGY BEHIND OUR LAWN CARE','tech.title':'The right robotic tool for the right lawn','tech.intro':'RoboGardener uses a range of robotic mowing tools alongside professional human oversight. Equipment is selected to suit the lawn, terrain, access and service requirements.','tech.tool':'ROBOTIC TOOL','tech.use1':'Regular lawns','tech.use2':'Challenging terrain','tech.use3':'Autonomous maintenance','tech.m1':'A controlled robotic mowing option for residential lawns, regular terrain and areas where precise operator control is useful.','tech.m2':'A more capable platform for challenging terrain, larger lawns and sites requiring additional traction and control.','tech.m3':'An autonomous mowing option suited to regular ongoing maintenance where consistent robotic mowing is appropriate.','tech.note':'Equipment shown represents tools available within our lawn-care approach. RoboGardener assesses each property before recommending a service method.',
      'quote.visualTitle':'Your Weekends<br>Are Yours Again','form.kicker':'FREE LAWN ASSESSMENT','form.title':'Get Your Lawn-Care Quote','form.intro':'Tell us about your lawn. We’ll review the property and contact you with a tailored quote.','form.name':'Full Name *','form.namePh':'Your name','form.phone':'Phone *','form.phonePh':'04xx xxx xxx','form.email':'Email *','form.emailPh':'you@example.com','form.address':'Service Address *','form.addressPh':'Street address, suburb, VIC','form.postcode':'Postcode *','form.area':'Approx. Lawn Area *','form.height':'Current Grass Height *','form.service':'Service Required *','form.info':'Additional Information','form.infoPh':'Access, slope, pets, preferred timing, lawn condition, etc.','form.photos':'Upload Lawn Photo (optional)','form.photoHelp':'JPG, PNG, WebP, HEIC or HEIF · maximum 10 MB','form.submit':'Get My Free Quote','form.newEnquiry':'Submit another enquiry','form.privacy':'🔒 Your details are used only to assess and respond to your enquiry.',
      'area.select':'Select lawn area','area.a1':'Under 100 m²','area.a2':'100–250 m²','area.a3':'250–500 m²','area.a4':'500–1,000 m²','area.a5':'1,000–2,000 m²','area.a6':'2,000 m²+','height.select':'Select grass height','height.h1':'Under 5 cm','height.h2':'5–10 cm','height.h3':'10–20 cm','height.h4':'20–40 cm','height.h5':'40 cm+ / overgrown','common.unsure':'Not sure','service.select':'Select service type','service.s1':'Robotic lawn mowing','service.s2':'Regular lawn maintenance','service.s3':'Edge trimming & detail work','service.s4':'Lawn health management','service.s5':'Custom lawn care plan','service.s6':'Commercial grounds maintenance',
      'estimate.label':'Indicative starting estimate','estimate.pending':'Complete lawn details to see an estimate','estimate.assess':'Assessment required — we’ll confirm after review','estimate.from':'From approximately','estimate.note':'Final pricing is confirmed after we review lawn condition, access, slope, service frequency and site requirements.',
      'steps.s1t':'Tell Us About Your Lawn','steps.s1d':'Share your address, lawn size, grass height and optional photos.','steps.s2t':'We Assess & Prepare a Quote','steps.s2d':'We review lawn condition, access and the right robotic + professional-care plan.','steps.s3t':'Enjoy a Better Lawn','steps.s3d':'Choose the right care plan and let us manage the mowing technology and lawn details.',
      'why.eyebrow':'WHY CHOOSE ROBOGARDENER?','why.title':'Technology + expertise = the perfect lawn','why.intro':'A smarter lawn-care service combining robotic mowing technology with Dr. Bill’s horticultural knowledge and long-term lawn-care experience','why.c1t':'Technology-led robotic mowing','why.c1d':'A modern service approach designed to make routine mowing quieter, more consistent and easier to manage.','why.c2t':'PhD-qualified horticultural expertise','why.c2d':'Science-led lawn care, practical horticultural knowledge and site-specific recommendations.','why.c3t':'18 years of lawn-mowing experience','why.c3d':'Professional, reliable and focused on long-term lawn presentation and health.',
      'services.eyebrow':'OUR SERVICES','services.title':'Smart care for a healthier, better-looking lawn','services.s1t':'Robotic Lawn Mowing','services.s1d':'Automatic, efficient and precise mowing using professional robotic technology.','services.s2t':'Regular Lawn Maintenance','services.s2d':'Scheduled mowing and lawn care to keep presentation consistent throughout the season.','services.s3t':'Edge Trimming & Detail Work','services.s3d':'Professional finishing around paths, fences, borders and areas robots cannot reach.','services.s4t':'Lawn Health Management','services.s4d':'Practical care recommendations focused on lawn health, appearance and ongoing improvement.','services.s5t':'Custom Lawn Care Plans','services.s5d':'Tailored service plans based on lawn area, grass condition, mowing frequency and property needs.','services.s6t':'Commercial Grounds Care','services.s6d':'Robot-assisted lawn care for selected commercial, strata and facility sites.',
      'founder.eyebrow':'FOUNDER-LED LAWN CARE','founder.title':'Expert judgement behind smarter lawn care','founder.p1':'RoboGardener is built around a simple principle: technology works best when it is matched to the lawn. Dr. Bill considers lawn condition, terrain, access and maintenance needs before selecting the right robotic and professional-care approach.','founder.f1':'PhD in Horticulture','founder.f2':'18 years lawn-care experience','founder.f3':'Melbourne-based service',
      'areas.eyebrow':'SERVICE AREA','areas.title':'Servicing Melbourne & surrounding areas','areas.desc':'Send us your postcode, lawn area and current grass height. We’ll confirm availability and prepare a suitable quote','areas.proof1':'Melbourne-based service','areas.proof2':'Residential & commercial','areas.proof3':'Site-specific recommendations','areas.cta':'Check My Area','footer.tagline':'Smart Lawn Care · A Greener Tomorrow','footer.services':'Services','footer.about':'RoboGardener','footer.ctaEyebrow':'MELBOURNE LAWN CARE','footer.ctaTitle':'Ready for a smarter lawn?','footer.rights':'All rights reserved.','footer.bottomTagline':'Smart care · Better lawns · A greener tomorrow','footer.contact':'Contact','footer.service':'Service','footer.melbourne':'Melbourne, Victoria','footer.quote':'Get a Free Quote'
    },
    zh: {
      'nav.demo':'预约免费演示','nav.services':'服务项目','nav.technology':'机器人割草','nav.why':'为什么选择我们','nav.commercial':'商业服务','nav.areas':'服务区域','nav.cta':'免费获取报价',
      'hero.eyebrow':'墨尔本智能草坪养护','hero.title':'更好的草坪<br><span>更聪明的割草方式</span><br>更专业的养护','hero.desc':'将机器人割草技术与专业草坪养护经验结合，为墨尔本住宅及商业物业提供更安静、更稳定、更专业的草坪管理服务。','hero.cta1':'免费草坪评估','hero.cta2':'了解我们的服务','hero.proof1':'园艺学博士专业背景','hero.proof2':'18 年草坪养护经验','hero.proof3':'安静、稳定的机器人割草','hero.trust':'专业监督与管理','hero.phd':'Dr. Bill · 园艺学博士','hero.exp':'18 年草坪养护经验',
      'market.eyebrow':'我们的客户','market.title':'为住宅与各类物业提供专业草坪养护','market.res.title':'住宅服务','market.res.desc':'为私人住宅及不同规模的住宅物业提供可靠、针对性的草坪养护。','market.res.i1':'私人住宅','market.res.i2':'大型住宅物业','market.res.i3':'私人退休住宅','market.com.title':'商业服务','market.com.desc':'为企业、共享物业及设施场地提供可扩展的专业草坪维护。','market.com.i1':'商业物业','market.com.i2':'分层物业 / 业主委员会','market.com.i3':'学校与幼儿教育机构','market.com.i4':'退休社区 / 管理型社区','market.com.i5':'办公室与设施场地',
      'tech.eyebrow':'草坪养护背后的科技','tech.title':'针对不同草坪，选择合适的机器人设备','tech.intro':'RoboGardener 将多种机器人割草设备与专业人工监督相结合，并根据草坪、地形、出入口及服务需求选择合适的工具','tech.tool':'机器人作业设备','tech.use1':'常规草坪','tech.use2':'复杂地形','tech.use3':'自主维护','tech.m1':'适合住宅草坪、常规地形以及需要操作人员精准控制的区域。','tech.m2':'针对更复杂地形、更大面积草坪，以及需要更强抓地力与控制能力的场地。','tech.m3':'适用于适合持续自主作业、需要规律维护的草坪场景。','tech.note':'页面展示的是 RoboGardener 草坪服务可采用的专业工具。实际服务方式会在评估物业情况后确定。',
      'quote.visualTitle':'周末时光<br>重新属于您','form.kicker':'免费草坪评估','form.title':'获取您的草坪养护报价','form.intro':'填写您的草坪信息，我们会评估现场情况并为您提供针对性的报价。','form.name':'姓名 *','form.namePh':'请输入姓名','form.phone':'电话 *','form.phonePh':'04xx xxx xxx','form.email':'邮箱 *','form.emailPh':'you@example.com','form.address':'服务地址 *','form.addressPh':'街道地址、城区、维多利亚州','form.postcode':'邮编 *','form.area':'草坪面积 *','form.height':'当前草高 *','form.service':'所需服务 *','form.info':'补充信息','form.infoPh':'例如出入口、坡度、宠物、希望服务时间、草坪状态等','form.photos':'上传草坪照片（可选）','form.photoHelp':'支持 JPG、PNG、WebP、HEIC 或 HEIF · 最大 10 MB','form.submit':'获取免费报价','form.newEnquiry':'再次提交询价','form.privacy':'🔒 您的信息仅用于评估并回复本次问询。',
      'area.select':'请选择草坪面积','area.a1':'100㎡以下','area.a2':'100–250㎡','area.a3':'250–500㎡','area.a4':'500–1,000㎡','area.a5':'1,000–2,000㎡','area.a6':'2,000㎡以上','height.select':'请选择当前草高','height.h1':'5cm 以下','height.h2':'5–10cm','height.h3':'10–20cm','height.h4':'20–40cm','height.h5':'40cm以上 / 明显过长','common.unsure':'不确定','service.select':'请选择服务类型','service.s1':'智能机器人割草','service.s2':'定期草坪维护','service.s3':'边缘修剪与细节处理','service.s4':'草坪健康管理','service.s5':'量身定制草坪护理方案','service.s6':'商业场地草坪维护',
      'estimate.label':'参考起步报价','estimate.pending':'填写草坪面积与草高后查看参考价格','estimate.assess':'需要人工评估 — 我们查看资料后确认','estimate.from':'参考约','estimate.note':'最终价格需结合草坪状态、出入口、坡度、服务频率及现场要求确认。',
      'steps.s1t':'告诉我们您的草坪情况','steps.s1d':'填写地址、草坪面积、草高，并可选择上传照片。','steps.s2t':'我们评估并准备报价','steps.s2d':'我们会查看草坪状态、出入口，并确定适合的机器人 + 专业人工养护方案。','steps.s3t':'享受更好的草坪','steps.s3d':'选择合适的服务方案，割草设备和细节维护由我们负责。',
      'why.eyebrow':'为什么选择 ROBOGARDENER？','why.title':'科技 + 专业 = 完美草坪','why.intro':'将智能机器人割草技术与 Dr. Bill 的园艺专业知识及长期草坪维护经验相结合，提供更现代、更稳定的草坪服务','why.c1t':'机器人技术驱动的割草方式','why.c1d':'以现代机器人技术提升日常割草的一致性、安静度和管理效率。','why.c2t':'园艺学博士专业背景','why.c2d':'结合科学方法、园艺专业知识和针对现场情况的草坪养护建议。','why.c3t':'18 年草坪割草经验','why.c3d':'注重专业、可靠的服务，以及草坪长期的外观和健康状态。',
      'services.eyebrow':'我们的服务','services.title':'智能护理，让草坪更健康、更漂亮','services.s1t':'智能机器人割草','services.s1d':'使用专业机器人技术自动规划、高效、精准完成草坪割草。','services.s2t':'定期草坪维护','services.s2d':'根据季节和草坪状态安排周期性割草与维护，让草坪保持整洁。','services.s3t':'边缘修剪与细节处理','services.s3d':'针对路径、围栏、花坛边缘及机器人难以覆盖的位置进行人工修整。','services.s4t':'草坪健康管理','services.s4d':'结合草坪状态提供实用养护建议，兼顾健康、外观与长期改善。','services.s5t':'量身定制草坪护理方案','services.s5d':'根据草坪面积、草高、维护频率和物业需求制定个性化服务计划。','services.s6t':'商业场地草坪维护','services.s6d':'为适合的商业物业、分层物业及设施场地提供机器人辅助草坪维护。',
      'founder.eyebrow':'创始人主导的专业草坪服务','founder.title':'用专业判断，让智能草坪养护真正发挥价值','founder.p1':'RoboGardener 的原则很简单：技术只有在真正适合草坪时才有价值。Dr. Bill 会结合草坪状态、地形、出入口和维护需求，再选择适合的机器人设备与专业人工养护方式。','founder.f1':'园艺学博士','founder.f2':'18 年草坪养护经验','founder.f3':'墨尔本本地服务',
      'areas.eyebrow':'服务区域','areas.title':'服务墨尔本及周边地区','areas.desc':'提交您的邮编、草坪面积与当前草高，我们会确认服务范围并准备适合的报价。','areas.proof1':'墨尔本本地服务','areas.proof2':'住宅与商业物业','areas.proof3':'针对现场情况提供建议','areas.cta':'查询我的区域','footer.tagline':'智能草坪养护 · 更绿色的明天','footer.services':'服务项目','footer.about':'RoboGardener','footer.ctaEyebrow':'墨尔本草坪养护','footer.ctaTitle':'准备好拥有更聪明的草坪养护了吗？','footer.rights':'版权所有。','footer.bottomTagline':'智能养护 · 更好的草坪 · 更绿色的明天','footer.contact':'联系我们','footer.service':'服务地区','footer.melbourne':'墨尔本，维多利亚州','footer.quote':'免费获取报价'
    }
  };
  const area=document.getElementById('lawnArea');const height=document.getElementById('grassHeight');const price=document.getElementById('estimatePrice');const preferredLanguage=document.getElementById('preferredLanguage');const photoHelp=document.getElementById('photoHelp');let currentLang=localStorage.getItem('robogardener-lang')||'en';
  const base={'0-100':55,'100-250':75,'250-500':105,'500-1000':145,'1000-2000':210,'2000+':290};const multiplier={'under5':1,'5-10':1.08,'10-20':1.22,'20-40':1.45,'40plus':1.8};
  function t(key){return translations[currentLang][key]||translations.en[key]||key}
  function applyLanguage(lang){currentLang=lang;document.documentElement.lang=lang==='zh'?'zh-CN':'en';localStorage.setItem('robogardener-lang',lang);if(preferredLanguage)preferredLanguage.value=lang==='zh'?'Chinese':'English';document.querySelectorAll('[data-i18n]').forEach(el=>{el.textContent=t(el.dataset.i18n)});document.querySelectorAll('[data-i18n-html]').forEach(el=>{el.innerHTML=t(el.dataset.i18nHtml)});document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{el.placeholder=t(el.dataset.i18nPlaceholder)});document.querySelectorAll('.lang-btn').forEach(btn=>{const active=btn.dataset.lang===lang;btn.classList.toggle('active',active);btn.setAttribute('aria-pressed',String(active));});const c1=document.getElementById('safeClaim1'),c2=document.getElementById('safeClaim2'),c3=document.getElementById('safeClaim3');if(c1){c1.textContent=t('why.c1t');if(c1.nextElementSibling)c1.nextElementSibling.textContent=t('why.c1d')}if(c2){c2.textContent=t('why.c2t');if(c2.nextElementSibling)c2.nextElementSibling.textContent=t('why.c2d')}if(c3){c3.textContent=t('why.c3t');if(c3.nextElementSibling)c3.nextElementSibling.textContent=t('why.c3d')}if(photoHelp)photoHelp.textContent=t('form.photoHelp');updateEstimate()}
  function updateEstimate(){if(!price||!area||!height)return;if(!area.value||!height.value){price.textContent=t('estimate.pending');return}if(area.value==='unknown'||height.value==='unknown'){price.textContent=t('estimate.assess');return}const raw=base[area.value]*multiplier[height.value];const rounded=Math.ceil(raw/5)*5;const upper=Math.ceil((rounded*1.25)/5)*5;price.textContent=`${t('estimate.from')} $${rounded}–$${upper}`}
  document.querySelectorAll('.lang-btn').forEach(btn=>btn.addEventListener('click',()=>applyLanguage(btn.dataset.lang)));
  area?.addEventListener('change',updateEstimate);height?.addEventListener('change',updateEstimate);
  const menuToggle=document.querySelector('.mobile-menu-toggle');const mainNav=document.getElementById('primaryNav');
  menuToggle?.addEventListener('click',()=>{const open=document.body.classList.toggle('nav-open');menuToggle.setAttribute('aria-expanded',String(open));menuToggle.setAttribute('aria-label',open?'Close navigation':'Open navigation');});
  mainNav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{document.body.classList.remove('nav-open');menuToggle?.setAttribute('aria-expanded','false');menuToggle?.setAttribute('aria-label','Open navigation');}));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.classList.contains('nav-open')){document.body.classList.remove('nav-open');menuToggle?.setAttribute('aria-expanded','false');menuToggle?.setAttribute('aria-label','Open navigation');menuToggle?.focus();}});
  applyLanguage(currentLang);
})();
